export const PERMISSIONS = {
  CERTIFICADO_LISTAR: 'certificado:listar',
  ESTUDIANTE_LISTAR: 'estudiante:listar',
  USUARIO_LISTAR: 'usuario:listar',
  PLANTILLA_LISTAR: 'plantilla:listar',
  INSTITUCION_VER: 'institucion:ver',
  AUDITORIA_VER: 'auditoria:ver',
}

export const PERMISSION_LABELS = {
  'usuario:listar': 'Ver lista de usuarios',
  'usuario:crear': 'Crear usuarios',
  'usuario:actualizar': 'Editar usuarios',
  'usuario:eliminar': 'Eliminar usuarios',
  'institucion:ver': 'Ver institución',
  'institucion:estadisticas': 'Ver estadísticas',
  'institucion:actualizar': 'Editar institución',
  'certificado:listar': 'Ver certificados',
  'certificado:ver': 'Ver detalle',
  'certificado:descargar': 'Descargar PDF',
  'certificado:emitir': 'Emitir certificados',
  'certificado:revocar': 'Revocar certificados',
  'estudiante:listar': 'Ver estudiantes',
  'estudiante:ver': 'Ver detalle',
  'estudiante:crear': 'Crear estudiantes',
  'estudiante:actualizar': 'Editar estudiantes',
  'estudiante:eliminar': 'Eliminar estudiantes',
  'plantilla:listar': 'Ver plantillas',
  'plantilla:ver': 'Ver detalle',
  'plantilla:crear': 'Crear plantillas',
  'plantilla:actualizar': 'Editar plantillas',
  'plantilla:archivar': 'Archivar plantillas',
  'auditoria:ver': 'Ver auditoría',
}
